-- Durable per-recipient email delivery for the four workspace events that need
-- mail. The existing notification writer remains the single authority for NDA
-- access and actor exclusion; this outbox mirrors only newly created events.
create table public.email_outbox (
  id bigint generated by default as identity primary key,
  notification_id uuid not null unique references public.notifications(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  card_id uuid references public.cards(id) on delete set null,
  comment_id uuid references public.comments(id) on delete set null,
  event_type text not null check (
    event_type in ('comment.created','card.created','card.reviewed','card.completed')
  ),
  subject text not null check (length(trim(subject)) between 1 and 180),
  body text not null default '' check (length(body) <= 5000),
  event_created_at timestamptz not null,
  created_at timestamptz not null default now(),
  attempt_count integer not null default 0 check (attempt_count between 0 and 8),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  lease_token uuid,
  sent_at timestamptz,
  discarded_at timestamptz,
  last_error text check (last_error is null or length(last_error) <= 500),
  constraint email_outbox_one_terminal_state check (
    num_nonnulls(sent_at,discarded_at) <= 1
  ),
  constraint email_outbox_lock_pair check (
    (locked_at is null) = (lease_token is null)
  )
);
create index email_outbox_pending
  on public.email_outbox(next_attempt_at,created_at,id)
  where sent_at is null and discarded_at is null;
create index email_outbox_recipient on public.email_outbox(recipient_id);
create index email_outbox_actor on public.email_outbox(actor_id);
create index email_outbox_workspace on public.email_outbox(workspace_id);
create index email_outbox_card on public.email_outbox(card_id) where card_id is not null;
create index email_outbox_comment on public.email_outbox(comment_id) where comment_id is not null;

alter table public.email_outbox enable row level security;
revoke all on public.email_outbox from public,anon,authenticated,service_role;
revoke all on sequence public.email_outbox_id_seq from public,anon,authenticated,service_role;

create function private.enqueue_workspace_email() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.event_type not in (
    'comment.created','card.created','card.reviewed','card.completed'
  ) then
    delete from public.email_outbox
    where notification_id = new.id and sent_at is null and discarded_at is null;
    return new;
  end if;

  insert into public.email_outbox(
    notification_id,recipient_id,actor_id,workspace_id,card_id,comment_id,
    event_type,subject,body,event_created_at
  ) values (
    new.id,new.recipient_id,new.actor_id,new.workspace_id,new.card_id,new.comment_id,
    new.event_type,new.subject,new.body,new.created_at
  )
  on conflict(notification_id) do update set
    recipient_id = excluded.recipient_id,
    actor_id = excluded.actor_id,
    workspace_id = excluded.workspace_id,
    card_id = excluded.card_id,
    comment_id = excluded.comment_id,
    event_type = excluded.event_type,
    subject = excluded.subject,
    body = excluded.body,
    event_created_at = excluded.event_created_at,
    next_attempt_at = clock_timestamp(),
    locked_at = null,
    lease_token = null,
    last_error = null
  where email_outbox.sent_at is null and email_outbox.discarded_at is null;
  return new;
end;
$$;
revoke all on function private.enqueue_workspace_email()
  from public,anon,authenticated,service_role;

create trigger enqueue_workspace_email
after insert or update of recipient_id,actor_id,workspace_id,card_id,comment_id,
  event_type,subject,body,event_key on public.notifications
for each row execute function private.enqueue_workspace_email();

-- Railway claims small batches with a service-role-only lease. Eligibility is
-- checked again at send time so access removal or workspace isolation changes
-- suppress mail that was queued before the authorization change.
create function public.claim_email_outbox(p_limit integer default 20)
returns table (
  outbox_id bigint,
  lease_token uuid,
  notification_id uuid,
  recipient_email text,
  recipient_name text,
  actor_name text,
  workspace_name text,
  workspace_id uuid,
  card_id uuid,
  event_type text,
  subject text,
  body text,
  event_created_at timestamptz,
  attempt_count integer
)
language plpgsql security definer set search_path = '' as $$
begin
  delete from public.email_outbox
  where id in (
    select id from public.email_outbox
    where coalesce(sent_at,discarded_at) < clock_timestamp() - interval '30 days'
    order by coalesce(sent_at,discarded_at),id
    limit 1000
  );

  update public.email_outbox o set
    discarded_at = clock_timestamp(),
    locked_at = null,
    lease_token = null,
    last_error = 'recipient_ineligible'
  where o.sent_at is null and o.discarded_at is null
    and (o.locked_at is null or o.locked_at < clock_timestamp() - interval '5 minutes')
    and (
      o.recipient_id = o.actor_id
      or not exists (
        select 1 from public.profiles p
        where p.id = o.recipient_id and p.active
          and position('@' in p.email) > 1
          and private.user_can_access_workspace(p.id,o.workspace_id)
      )
    );

  update public.email_outbox o set
    discarded_at = clock_timestamp(),
    locked_at = null,
    lease_token = null,
    last_error = coalesce(o.last_error,'retry_limit_reached')
  where o.sent_at is null and o.discarded_at is null
    and o.attempt_count >= 8
    and (o.locked_at is null or o.locked_at < clock_timestamp() - interval '5 minutes');

  return query
  with candidates as (
    select o.id
    from public.email_outbox o
    join public.profiles recipient on recipient.id = o.recipient_id
    where o.sent_at is null and o.discarded_at is null
      and o.attempt_count < 8
      and o.next_attempt_at <= clock_timestamp()
      and (o.locked_at is null or o.locked_at < clock_timestamp() - interval '5 minutes')
      and o.recipient_id <> o.actor_id
      and recipient.active
      and position('@' in recipient.email) > 1
      and private.user_can_access_workspace(recipient.id,o.workspace_id)
    order by o.event_created_at,o.id
    for update of o skip locked
    limit least(greatest(coalesce(p_limit,20),1),100)
  ), claimed as (
    update public.email_outbox o set
      locked_at = clock_timestamp(),
      lease_token = gen_random_uuid(),
      attempt_count = o.attempt_count + 1
    from candidates c
    where o.id = c.id
    returning o.*
  )
  select
    claimed.id,
    claimed.lease_token,
    claimed.notification_id,
    recipient.email,
    recipient.name,
    coalesce(actor.name,'Ehemaliges Mitglied'),
    workspace.name,
    claimed.workspace_id,
    claimed.card_id,
    claimed.event_type,
    claimed.subject,
    claimed.body,
    claimed.event_created_at,
    claimed.attempt_count
  from claimed
  join public.profiles recipient on recipient.id = claimed.recipient_id
  left join public.profiles actor on actor.id = claimed.actor_id
  join public.workspaces workspace on workspace.id = claimed.workspace_id
  order by claimed.event_created_at,claimed.id;
end;
$$;
revoke all on function public.claim_email_outbox(integer)
  from public,anon,authenticated;
grant execute on function public.claim_email_outbox(integer) to service_role;

create function public.finish_email_outbox(
  p_id bigint,
  p_lease uuid,
  p_succeeded boolean,
  p_error text default null
) returns boolean
language plpgsql security definer set search_path = '' as $$
declare affected integer;
begin
  if p_id is null or p_lease is null or p_succeeded is null then return false; end if;

  update public.email_outbox o set
    sent_at = case when p_succeeded then clock_timestamp() else null end,
    discarded_at = case
      when not p_succeeded and o.attempt_count >= 8 then clock_timestamp()
      else null
    end,
    next_attempt_at = case
      when p_succeeded or o.attempt_count >= 8 then o.next_attempt_at
      else clock_timestamp() + make_interval(
        secs => least(
          3600,
          (30 * power(2,least(greatest(o.attempt_count - 1,0),7)))::integer
        )
      )
    end,
    locked_at = null,
    lease_token = null,
    last_error = case
      when p_succeeded then null
      else left(coalesce(nullif(trim(p_error),''),'delivery_failed'),500)
    end
  where o.id = p_id and o.lease_token = p_lease
    and o.sent_at is null and o.discarded_at is null;
  get diagnostics affected = row_count;
  return affected = 1;
end;
$$;
revoke all on function public.finish_email_outbox(bigint,uuid,boolean,text)
  from public,anon,authenticated;
grant execute on function public.finish_email_outbox(bigint,uuid,boolean,text)
  to service_role;
